import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Session from './session'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex items-center justify-center bg-gray-900`}>
        <Session> 
          {children}
        </Session>
      </body>
    </html>
  )
}
